### ISSUE TITLE
combine the two projects

### ISSUE THREAD

**Issue by mvayngrib** [LeoFidjeland/react-native-barcode#1]
first of all, thanks for the lib!

currently I have to add both projects to Libraries even if I just want to use QRCode alone. Can you combine them into project or alternately, separate them into two separate projects?

**Comment by mvayngrib** [comment]
nevermind, forgot i can do

``` js
var QRCode = require('react-native-barcode/QR/QRCode')
```

instead of 

``` js
var QRCode = require('react-native-barcode').QRCode
```

**Comment by LeoFidjeland** [comment]
Thanks for the comment!

I guess it should be refactored to:

```
var QRCode = require('react-native-barcode/QRCode')
```

Let me know if you have any other issues :)

**Comment by mvayngrib** [comment]
yea, thanks, very happy with the lib so far
