### ISSUE TITLE
Support modern React Native

### ISSUE THREAD

**Issue by jdmunro** [LeoFidjeland/react-native-barcode#5]
I was just wondering if you had plans to support a modern React Native version?

The main issue is this:

```
var React = require('react-native');
```

React is no longer exported by React Native, it is an explicit import of its own, e.g.

```
var React = require('react');
```

**Comment by LeoFidjeland** [comment]
I'm not working with this library any more, but if you did a pull request
with this, I'de be happy to approve it! :)

ons 16 nov. 2016 kl. 17:28 skrev James Munro notifications@github.com:

**Comment by jdmunro** [comment]
No worries! I've fixed this locally, so I'll try and put together a PR to modernise for newer version of RN.

**Comment by LeoFidjeland** [comment]
great! thanks!

ons 16 nov. 2016 kl 19:56 skrev James Munro notifications@github.com:

**Comment by umer990** [comment]
I did request to update! Can you please allow me?

**Comment by LeoFidjeland** [comment]
I'm on vacation in Sri Lanka now unfortunately :)

But I'll move it in upstream when I'm back in January!
ons 14 dec. 2016 kl. 01:51 skrev umer990 <notifications@github.com>:

**Comment by LeoFidjeland** [comment]
Should be resolved now, I merged the fix from a fork.

https://github.com/LeoFidjeland/react-native-barcode/pull/7
