### ISSUE TITLE
Unable to access the component!

### ISSUE THREAD

**Issue by umer990** [LeoFidjeland/react-native-barcode#6]
getting this on "import AztecCode from "react-native-barcode" or on var AztecCode = require("react-native-barcode").AztecCode;

![screen shot 2016-12-12 at 6 40 39 pm](https://cloud.githubusercontent.com/assets/13518873/21109764/ca2fa2d4-c09a-11e6-965c-a3c6619ca15b.png)

**Comment by LeoFidjeland** [comment]
Resolved in https://github.com/LeoFidjeland/react-native-barcode/pull/7
